baseURL = "https://dikatrio.xyz"
languageCode = "en-us"
title = "Kostis Katrioplas"
theme = "square"

pluralizeListTitles = false
paginate = 20

[menu]
  [[menu.main]]
  name = "home"
  weight = 1
  url = "/"
 [[menu.main]]
   name = "posts"
   weight = 1
   url = "/posts"
 [[menu.main]]
   name = "links"
   weight = 2
   url = "/links"
 [[menu.main]]
   name = "readme"
   weight = 3
   url = "/readme"

[params]
 GithubID = "kkatrio"
 TwitterID = "bitonic5000"
 Email = "kokatrio@gmail.com"
 Name = "Kostis Katrioplas"
