baseURL = "https://dikatrio.xyz"
languageCode = "en-us"
title = "Kostas Katrioplas"
theme = "square"

pluralizeListTitles = false
paginate = 20

[menu]
  [[menu.main]]
  name = "home"
  weight = 1
  url = "/"
 [[menu.main]]
   name = "projects"
   weight = 1
   url = "/projects"
 [[menu.main]]
   name = "posts"
   weight = 2
   url = "/posts"
 [[menu.main]]
   name = "links"
   weight = 3
   url = "/links"

[params]
 GithubID = "kkatrio"
 TwitterID = "bitonic5000"
 Email = "kokatrio@gmail.com"
 Name = "Konstantinos Katrioplas"

 # not needed if we link the resource in a html header
 #custom_css = ["css/cv.css"]

[markup.goldmark.renderer]
unsafe= true
