baseURL = "https://dikatrio.xyz"
languageCode = "en-us"
title = "Konstantinos Katrioplas"
theme = "square"

pluralizeListTitles = false

[pagination]
  pagerSize = 20

[menu]
  [[menu.main]]
  name = "home"
  weight = 1
  url = "/"
 [[menu.main]]
   name = "projects"
   weight = 1
   url = "/projects"
 [[menu.main]]
   name = "blog"
   weight = 2
   url = "/blog"
 [[menu.main]]
   name = "bookself"
   weight = 3
   url = "/bookself"
 [[menu.main]]
   name = "bookmarks"
   weight = 4
   url = "/bookmarks"

[params]
 GithubID = "kkatrio"
 Email = "kokatrio@gmail.com"
 Name = "Konstantinos Katrioplas"
 # enable only on the posts we want maths
 math = false

 # not needed if we link the resource in a html header
 #custom_css = ["css/cv.css"]

# render raw html in index.md files
[markup.goldmark.renderer]
unsafe= true

# render latex maths formulas
# https://gohugo.io/content-management/mathematics/
[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
