baseURL = "https://dikatrio.xyz/"
languageCode = "en-us"
title = "Konstantinos Katrioplas"
theme = "nix"
pluralizeListTitles = false
paginate = 5

[menu]
 [[menu.header]]
   name = "posts"
   weight = 1
   url = "/posts"
 [[menu.header]]
   name = "readme"
   weight = 2
   url = "/readme"
   

[params]
  GithubID = "kkatrio"
  TwitterID = "bitonic5000"
  Name = "Konstantinos Katrioplas"
  HeaderUsername = ""
  HeaderHostname = ""
  Email = "kokatrio@gmail.com"
  About = "Konstantinos Katrioplas is a passionate programmer and a physicist. He loves math, geometry, numbers and computers. He likes contributing to open source projects like cgal and scikit-learn. When he is not writing code he likes reading books, helping with the house garden or learning about networks and the internet."
  ProfilePicture = "/img/phenomena.jpg"
  GoogleAnalytics = "UA-105597427-1"
