baseURL = "https://dikatrio.xyz/"
languageCode = "en-us"
title = "Konstantinos Katrioplas"
theme = "nix"
pluralizeListTitles = false
paginate = 5

[menu]
  [[menu.header]]
    name = "readme"
    weight = 1
    url = "/readme"

[params]
  GithubID = "kkatrio"
  TwitterID = "bitonic5000"
  LinkedInID = "konstantinoskatrioplas"
  Name = "Konstantinos Katrioplas"
  HeaderUsername = ""
  HeaderHostname = ""
  Email = "kokatrio@gmail.com"
  About = "Hello"
  ProfilePicture = "/img/art.jpg"
  GoogleAnalytics = "UA-105597427-1"
